// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`
// Extended with project-specific bindings and secrets

interface CloudflareBindings {
  // D1 Database
  DB: D1Database;

  // Non-secret vars (set in wrangler.toml [vars])
  ADMIN_USERNAME: string;
  HOST_VERSIONS_API: string;

  // Secrets (set via dashboard or `wrangler pages secret put`)
  GITHUB_TOKEN: string;
  ADMIN_PASSWORD: string;
  JWT_SECRET: string;
  NEXT_PUBLIC_EMAILJS_SERVICE_ID: string;
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: string;
  NEXT_PUBLIC_EMAILJS_USER_ID: string;
  CLOUDFLARE_API_TOKEN: string;
}

interface CloudflareEnv extends CloudflareBindings {}
