// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  DB: D1Database;
}

// Merge custom bindings into the CloudflareEnv interface used by @opennextjs/cloudflare
declare global {
  interface CloudflareEnv extends CloudflareBindings {}
}
