name = "zviel-website"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "zviel-website-db"
database_id = "9b4a91e8-b258-4a5c-b672-b863d1207550"